---

- name: Create Jellyfin directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items:
    - "{{ jellyfin_config_directory }}"

- name: Jellyfin Docker Container
  docker_container:
    name: "{{ jellyfin_container_name }}"
    image: "{{ jellyfin_container_store }}/{{ jellyfin_container_name }}:{{ jellyfin_version }}"
    pull: true
    volumes:
      - "{{ jellyfin_config_directory }}:/config:"
      - "{{ jellyfin_tv_directory }}:/data/tv:{{ jellyfin_tv_permissions }}"
      - "{{ jellyfin_movies_directory }}:/data/movies:{{ jellyfin_movies_permissions }}"
    ports:
      - "{{ jellyfin_port_http }}:8096"
      - "{{ jellyfin_port_https }}:8920"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ jellyfin_uid | string }}"
      PGID: "{{ jellyfin_gid | string }}"
    restart_policy: unless-stopped
    memory: "{{ jellyfin_memory }}"
    labels:
      traefik.enable: "{{ jellyfin_available_externally }}"
      traefik.http.routers.jellyfin.rule: "Host(`{{ jellyfin_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.jellyfin.tls.certresolver: "letsencrypt"
      traefik.http.routers.jellyfin.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.jellyfin.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
