---
portainer_enabled: false
portainer_available_externally: false
portainer_container_name: portainer
portainer_container_store: portainer
portainer_config_directory: "{{ docker_app_data }}/portainer"
portainer_version: latest
portainer_port: 9000
portainer_hostname: "portainer"
portainer_memory: 1g
