---

- name: Create Gitea group account
  group:
    name: git
    gid: "{{ gitea_gid | string }}"
    state: present

- name: Create Gitea user account
  user:
    name: git
    uid: "{{ gitea_uid | string }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: git
    
- name: Create Gitea Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    recurse: yes
  with_items:
    - "{{ gitea_config_directory }}"
    - "{{ gitea_db_config_directory }}"

# - name: mariadb Docker Container
#   docker_container:
#     name: "{{ gitea_db_container }}"
#     image: "{{ mariadb_container_store }}/{{ mariadb_container_name }}:{{ mariadb_version }}"
#     pull: true
#     volumes:
#       - "{{ gitea_db_config_directory }}/config:/config"
#     ports:
#       - "{{ mariadb_port }}:3306/tcp"
#     env:
#       TZ: "{{ system.timezone }}"
#       PUID: "{{ user_uid | string }}"
#       PGID: "{{ user_gid | string }}"
#       MYSQL_USER: "{{ gitea_db_user }}"
#       MYSQL_PASSWORD: "{{ mariadb_root_password }}"
#       MYSQL_DATABASE: "{{ gitea_db_name }}"
#       MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
#       restart_policy: unless-stopped

- name: Create MySQL container for Gitea
  docker_container:
    name: "{{ gitea_db_container }}"
    image: mysql:5.7
    pull: true
    volumes:
      - "{{ gitea_db_config_directory }}:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "gitea"
      MYSQL_USER: "gitea"
      MYSQL_PASSWORD: "gitea"
      MYSQL_ROOT_PASSWORD: "gitea"
    restart_policy: unless-stopped
    memory: "{{ gitea_mysql_memory }}"

- name: Create Gitea container
  docker_container:
    name: "{{ gitea_container_name }}"
    image: "{{ gitea_container_store }}/{{ gitea_container_name }}:{{ gitea_version }}"
    pull: true
    links:
        - "{{ gitea_db_container }}:db"
    volumes:
      - "{{ gitea_config_directory }}:/data:rw"
    ports:
      - "{{ gitea_port_http }}:3000"
      - "{{ gitea_port_ssh }}:22"
    env:
      DB_TYPE: "mysql"
      DB_HOST: "db:3306"
      DB_NAME: "gitea"
      DB_USER: "gitea"
      DB_PASSWD: "gitea"
      RUN_MODE: "prod"
      USER_UID: "{{ gitea_uid | string }}"
      USER_GID: "{{ gitea_gid | string }}"
      # SSH_DOMAIN: "{{ ansible_nas_hostname }}"
      # SSH_PORT: "{{ gitea_port_ssh }}"
      # ROOT_URL: "http://{{ ansible_nas_hostname }}:{{ gitea_port_http }}/"
    restart_policy: unless-stopped
    memory: "{{ gitea_memory }}"
    labels:
      traefik.enable: "{{ gitea_available_externally }}"
      traefik.http.routers.gitea.rule: "Host(`{{ gitea_hostname }}.{{ external_domain }}`)"
      traefik.http.routers.gitea.tls.certresolver: "letsencrypt"
      traefik.http.routers.gitea.tls.domains[0].main: "{{ external_domain }}"
      traefik.http.routers.gitea.tls.domains[0].sans: "*.{{ external_domain }}"
      traefik.http.services.gitea.loadbalancer.server.port: "3000"
