---

- name: Create sonarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items:
    - "{{ sonarr_config_directory }}"

- name: sonarr Docker Container
  docker_container:
    name: "{{ sonarr_container_name }}"
    image: "{{ sonarr_container_store }}/{{ sonarr_container_name }}:{{ sonarr_version }}"
    pull: true
    volumes:
      - "{{ sonarr_config_directory }}/config:/config:rw"
      - "{{ media_downloads }}:/downloads:rw"
      - "{{ media_tv }}:/tv:rw"
    ports:
      - "{{ sonarr_port }}:8989"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ user_uid | string }}"
      PGID: "{{ user_gid | string }}"
    restart_policy: unless-stopped
    memory: "{{ sonarr_memory }}"
    labels:
      traefik.enable: "{{ sonarr_available_externally }}"
      traefik.http.routers.sonarr.rule: "Host(`{{ sonarr_hostname }}.{{ external_domain }}`)"
      traefik.http.routers.sonarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.sonarr.tls.domains[0].main: "{{ external_domain }}"
      traefik.http.routers.sonarr.tls.domains[0].sans: "*.{{ external_domain }}"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
