---

- hosts: vultr1
  user: arch
  become: yes
  roles:

    - role: base-packages

    # - role: geerlingguy.docker
    #   tags:
    #     - docker

    - role: plex
      tags:
        - plex
      when: (plex_enabled | default(False))

    - role: jellyfin
      tags:
        - jellyfin
      when: (jellyfin_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: sickchill
      tags:
        - sickchill
      when: (sickchill_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: heimdall
      tags:
        - heimdall
      when: (heimdall_enabled | default(False))

    - role: bookstack
      tags:
        - bookstack
      when: (bookstack_enabled | default(False))

